### ISSUE TITLE
Cant seem to get this to work

### ISSUE THREAD

**Issue by AndySpawn** [Nastas95/SteamClip#2]
Ive downloaded the executable and ran it in Desktop Mode on my Steam  Deck, I get the "Game IDs Downloaded in config folder" dialogue, but the window is completely blank. I cant select my SteamID as the drop down doesn't open.

I know I have clips because I can  see them in Steam.

![Image](https://github.com/user-attachments/assets/b9446079-fc02-4241-87a7-6f2cc50e1fc4)

**Comment by Nastas95** [comment]
Go into the config folder (Home/.config/SteamClip) and delete the SteamClip.conf file, then launch SteamClip again. LMK

I'm going to update SteamClip so that this problem shouldn't happen anymore

**Comment by Nastas95** [comment]
Just released a new version, should work now. If it doesn't and it continues to show this screen to you then there is something wrong with the selected userdata folder or your steamID. Can you provide me with some details of your system? Are you on the SteamDeck? If not: how did you install Steam?

Thanks

**Comment by AndySpawn** [comment]
Thanks for replying.

I tried your first solution but it didn't make any difference.

I tried deleting SteamClip and downloading the latest version. If I select "Standard" I'm stuck with the same issue I had in the previous version. If I click "Flatpak" I get an error message saying that my userdata folder is not valid. If I select "Manual" and point it to my userdata folder, I get the same error message saying that my userdata folder is not valid. I'm pointing it to the folder; 
/home/deck/.local/share/Steam/userdata

I'm using the SteamDeck OLED 1tb model which I've swapped the M.2 SSD for a 2tb.

**Comment by Nastas95** [comment]
I think I got the problem. Right now SteamClip only converts clips that are Manually Created, not the background recordings.

In Fact SteamClip checks if the Userdata folder selected is valid by searching for a specific directory, which is /userdata/SteamID/gamerecordings/clips

in your case there is no "clips" folder but a "video" folder due to (i guess) Background recording.

I'm already working on an update, should be coming soon

**Comment by Nastas95** [comment]
Hi, check out the latest release. it should work now!

**Comment by AndySpawn** [comment]
Dude, you're awesome! Thank you so much!

I tested out the new v2.8.1 and it works! The Flatpak option still throws up the invalid folder error, but the Standard option worked for me.

I hadn't realised the Steam Deck handles the background recordings differently to the manual recordings.
